language: ruby

services:
  - mongodb

before_install:
  - gem update bundler

rvm:
  - 2.1.5
  - 2.2.1
  - 2.3.0

env:
  - "RAILS_VERSION=4.0"
  - "RAILS_VERSION=4.1"
  - "RAILS_VERSION=4.2"
  - "RAILS_VERSION=5.0"

matrix:
   exclude:
     - env: "RAILS_VERSION=5.0"
       rvm: 2.1.5
     - env: "RAILS_VERSION=5.0"
       rvm: 2.2.1
